### ISSUE TITLE
背景をスクロールさせないようにする

### ISSUE THREAD

**Issue by konojunya** [moriyuu/react-semi-modal#1]
https://qiita.com/gonshi_com/items/5a86fc415dcccfb04e2a

ここらへんでいけるんじゃね

**Comment by moriyuu** [comment]
@konojunya Create PR, please! ❤️

**Comment by moriyuu** [comment]
https://twitter.com/_ideyuta/status/1140900047019638784

**Comment by konojunya** [comment]
ふぁいと❤️

**Comment by moriyuu** [comment]
https://github.com/moriyuu/react-semi-modal/pull/2
